apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-app
        image: 533267389601.dkr.ecr.us-east-1.amazonaws.com/eks-cluster:latest
        ports:
        - containerPort: 80
