apiVersion: v1
kind: Service
metadata:
   name: tomcat-app-service
spec:
  selector:
    app: java-tomcat
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007
  type: NodePort